on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lints:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v5
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v12
        with:
          name: snowflakeos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          for pkg in `ls packages`; do
            nix build .#${pkg}
          done
